title: Idle Science
description: >-
    "Idle Science", your go-to destination for exploring the untapped potential of science in achieving a more equitable and sustainable world.

url: https://idle.science
paginate_path: /blog/page:num/
permalink: /blog/:title

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

social:
    github: idlescience
    twitter: IdleScience
    email: secci.jr@gmail.com

google_analytics: 'G-8QPR7MQ5QD'

disqus:
    shortname: https-idle-science

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/