# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Idle Science
email: secci.jr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to "Idle Science", your go-to destination for exploring the untapped potential of science in achieving a more equitable and sustainable world.

  In an era characterized by profound global challenges such as climate change, social inequalities, and environmental degradation, it is imperative that we harness the power of scientific knowledge and innovation for the betterment of society. However, despite the incredible advancements in scientific research and understanding, there exists a persistent gap between the science available to us and its practical application in addressing critical issues.

  Our website aims to shed light on this gap and advocate for the utilization of science when it is most needed, for the promotion of equity and sustainability. We believe that science should not remain confined within academic circles or industry laboratories, but should actively inform policies, drive decision-making processes, and inspire collective action.

  Through thought-provoking articles, engaging multimedia content, and interviews with experts, we delve into the root causes of why science is often overlooked or underutilized in the pursuit of equity and sustainability. We explore the intricate dynamics between science, society, and governance, highlighting the systemic barriers that hinder effective science-based solutions from being implemented.

  By presenting inspiring case studies, successful initiatives, and transformative approaches, we showcase the immense potential of science as a catalyst for positive change. Our website serves as a platform for scientists, policymakers, activists, and concerned individuals to come together, exchange ideas, and collaborate towards a more inclusive, just, and sustainable future.

  Whether you are a scientist seeking to make your research more accessible and impactful, a policymaker searching for evidence-based solutions, or an engaged citizen looking to understand the role of science in creating a fairer and greener world, our website provides a wealth of knowledge and resources to support your journey.

  Join us as we bridge the gap between science and action, encouraging the widespread integration of scientific principles and findings into the realms of social justice, environmental conservation, and sustainable development. Together, let's harness the full potential of science to forge a path towards a future that prioritizes equity, preserves our planet, and safeguards the well-being of all.

domain: blog.idle.science
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.idle.science # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: IdleScience
github_username:  idlescience

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
